Fix  'Unknown' country bug
mikecao/umami pull request #1115
Opened 2022-04-18 17:27 UTC by briancao

Fix null country showing as [Object object] instead of 'Unknown'

2022-04-18 19:01 UTC, mikecao requested changes

2022-04-18 19:01 UTC, mikecao commented on components/common/FilterLink.js
> +            : label || value}
Too confusing

2022-04-18 19:34 UTC, briancao commented on components/common/FilterLink.js
> +            : label || value}
removed safeDecodrURI alltogether.

2022-04-20 15:44 UTC, merged

2022-06-21 07:49 UTC, pqvst commented
This PR broke URL rendering for non-English languages, such as Arabic, Japanese, Chinese, Korean, etc. #1171